"""
Seed the `dgca_monthly_avg` reference table.

TWO MODES, AND THE DIFFERENCE MATTERS
  --csv <file>   Load real figures transcribed from a DGCA / MoCA publication.
                 Rows are marked with the citation you pass in --source.
  (default)      Generate ILLUSTRATIVE placeholder rows, every one of them
                 stamped `SYNTHETIC-PLACEHOLDER` in `source_note`.

The placeholder path exists so the backtest *mechanism* can be demonstrated on
a machine with no DGCA file to hand. It is not a substitute for the real data
and the codebase refuses to let it pretend otherwise: `apix.index.backtest`
detects the marker and sets `uses_placeholder_reference`, which forces the
caveat into the CLI output, the /v1/backtest response and the dashboard badge.

Do not remove the marker to make a demo look better. The whole point of this
project is that the provenance of a number travels with it.

CSV FORMAT
    route,month,avg_fare,passenger_count
    DEL-BOM,2026-10,6120.50,1042311
    DEL-BLR,2026-10,6890.00,

`month` is YYYY-MM. `passenger_count` is optional.
"""
from __future__ import annotations

import argparse
import csv
import math
import sys
from pathlib import Path

from sqlalchemy import delete, select

from apix.config.loader import load_routes
from apix.db.models import DgcaMonthlyAvg
from apix.db.session import create_all, session_scope
from apix.index.backtest import PLACEHOLDER_MARKER

PLACEHOLDER_NOTE = (
    f"{PLACEHOLDER_MARKER}: illustrative monthly average generated by "
    "scripts/seed_dgca.py. NOT transcribed from any DGCA or MoCA publication. "
    "Replace with real figures via `apix seed-dgca --csv <file>` before quoting "
    "any backtest result as validation."
)


def _months_between(start: str, end: str) -> list[str]:
    sy, sm = (int(x) for x in start.split("-"))
    ey, em = (int(x) for x in end.split("-"))
    out = []
    y, m = sy, sm
    while (y, m) <= (ey, em):
        out.append(f"{y:04d}-{m:02d}")
        m += 1
        if m == 13:
            y, m = y + 1, 1
    return out


def seed_placeholder(start: str, end: str, replace: bool) -> int:
    """
    Generate a smooth, clearly-labelled reference series.

    The shape is deterministic (a mild seasonal sine plus drift) rather than
    random, so re-running produces the same numbers and a demo is reproducible.
    It is anchored on each route's `sim_base_fare` purely to be the right order
    of magnitude — it carries no information about actual market fares.
    """
    routes = load_routes().routes
    months = _months_between(start, end)
    rows = 0
    with session_scope() as session:
        if replace:
            session.execute(delete(DgcaMonthlyAvg))
        for r in routes:
            for i, month in enumerate(months):
                mm = int(month.split("-")[1])
                # Peak around Oct-Nov (festival season), trough in monsoon.
                seasonal = 1.0 + 0.12 * math.sin((mm - 4) / 12.0 * 2 * math.pi)
                drift = 1.0 + 0.004 * i
                avg = round(r.sim_base_fare * 1.28 * seasonal * drift, 2)
                existing = session.scalars(
                    select(DgcaMonthlyAvg).where(
                        DgcaMonthlyAvg.route == r.route,
                        DgcaMonthlyAvg.month == month,
                    )
                ).first()
                if existing:
                    existing.avg_fare = avg
                    existing.source_note = PLACEHOLDER_NOTE
                else:
                    session.add(
                        DgcaMonthlyAvg(
                            route=r.route,
                            month=month,
                            avg_fare=avg,
                            passenger_count=None,
                            source_note=PLACEHOLDER_NOTE,
                        )
                    )
                rows += 1
    return rows


def seed_from_csv(path: Path, source: str, replace: bool) -> int:
    known = set(load_routes().route_codes)
    rows = 0
    with session_scope() as session:
        if replace:
            session.execute(delete(DgcaMonthlyAvg))
        with path.open("r", encoding="utf-8", newline="") as fh:
            for lineno, rec in enumerate(csv.DictReader(fh), start=2):
                route = (rec.get("route") or "").strip().upper()
                month = (rec.get("month") or "").strip()
                if route not in known:
                    print(f"  line {lineno}: route {route!r} not in routes.yaml — skipped",
                          file=sys.stderr)
                    continue
                try:
                    avg = float((rec.get("avg_fare") or "").replace(",", ""))
                except ValueError:
                    print(f"  line {lineno}: unparseable avg_fare — skipped", file=sys.stderr)
                    continue
                pax_raw = (rec.get("passenger_count") or "").replace(",", "").strip()
                pax = int(float(pax_raw)) if pax_raw else None

                existing = session.scalars(
                    select(DgcaMonthlyAvg).where(
                        DgcaMonthlyAvg.route == route, DgcaMonthlyAvg.month == month
                    )
                ).first()
                if existing:
                    existing.avg_fare = avg
                    existing.passenger_count = pax
                    existing.source_note = source
                else:
                    session.add(
                        DgcaMonthlyAvg(
                            route=route, month=month, avg_fare=avg,
                            passenger_count=pax, source_note=source,
                        )
                    )
                rows += 1
    return rows


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument("--csv", type=Path, help="load real DGCA figures from a CSV file")
    ap.add_argument(
        "--source",
        default="",
        help="citation for --csv rows, e.g. 'DGCA Monthly Traffic Report, Oct 2026, Table 3'",
    )
    ap.add_argument("--start", default="2026-06", help="first month for placeholder mode")
    ap.add_argument("--end", default="2026-12", help="last month for placeholder mode")
    ap.add_argument("--replace", action="store_true", help="clear the table first")
    args = ap.parse_args(argv)

    create_all()

    if args.csv:
        if not args.csv.exists():
            print(f"error: {args.csv} does not exist", file=sys.stderr)
            return 1
        if not args.source:
            print(
                "error: --source is required with --csv. A reference figure "
                "without a citation is not a reference figure.",
                file=sys.stderr,
            )
            return 1
        n = seed_from_csv(args.csv, args.source, args.replace)
        print(f"Loaded {n} DGCA row(s) from {args.csv}")
        print(f"  cited as: {args.source}")
        return 0

    n = seed_placeholder(args.start, args.end, args.replace)
    print(f"Seeded {n} ILLUSTRATIVE reference row(s), {args.start}..{args.end}")
    print()
    print("  !! These are NOT real DGCA figures. Every row is stamped")
    print(f"  !! {PLACEHOLDER_MARKER}, and any backtest run against them will")
    print("  !! carry that caveat through the CLI, the API and the dashboard.")
    print("  !! Load real data with:  apix seed-dgca --csv <file> --source '<citation>'")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
